name: mysecretstore
componentType: secretstores.azure.keyvault
version: v1
metadata:
- name: vaultName
  value: "kvDotNet2022"
- name: azureTenantId
  value: "3a465f8a-b004-45a3-a74e-2b479766bd54"
- name: azureClientId
  value: "49e8c131-0c22-4030-a34d-3f390f6869bd"
- name: azureClientSecret
  secretRef: clientsecret
secrets:
- name: clientsecret
  value: "m2g8Q~-_DyZn5QHGG.TjEShhouSJIHOYOjS7McFJ"
scopes:
- capacityplanner