apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rater-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "15 * * * * *" # valid cron schedule  
scopes:
  - rater