apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
spec:
  policies:
    timeouts:
    #  general: 5s
    #  large: 10s
    retries:
    #  retryForever:
    #    policy: exponential
    #    maxInterval: 15s
    #    maxRetries: -1 # retry indefinitely
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 10s 
        trip: consecutiveFailures > 2
  targets:
    apps:
      catalog:
      #  timeout: large
        circuitBreaker: simpleCB
    components:


