apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: configuration
spec:
  features:
    - name: PubSub.Routing
      enabled: true
    - name: ServiceInvocation.NoDefaultContentType
      enabled: true   
    - name: Resiliency
      enabled: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"